export const FETCH_NEW_BOOKS_REQUESTED = "FETCH_NEW_BOOKS_REQUESTED" as const;
export const FETCH_NEW_BOOKS_SUCCESS = "FETCH_NEW_BOOKS_SUCCESS" as const;
export const FETCH_NEW_BOOKS_FAILURE = "FETCH_NEW_BOOKS_FAILURE" as const;

export const FETCH_BOOK_DETAILS_REQUESTED = "FETCH_BOOK_DETAILS_REQUESTED" as const;
export const FETCH_BOOK_DETAILS_SUCCESS = "FETCH_BOOK_DETAILS_SUCCESS" as const;
export const FETCH_BOOK_DETAILS_FAILURE = "FETCH_BOOK_DETAILS_FAILURE" as const;

export const CHANGE_SORT_TYPE = "CHANGE_SORT_TYPE" as const;
export const CHANGE_PUBLISHER_FILTER_VALUE = "CHANGE_PUBLISHER_FILTER_VALUE" as const;
export const CHANGE_AUTHORS_FILTER_VALUE = "CHANGE_AUTHORS_FILTER_VALUE" as const;

export const ADD_BOOK_TO_CART = "ADD_BOOK_TO_CART" as const;
export const REMOVE_BOOK_FROM_CART = "REMOVE_BOOK_FROM_CART" as const;
export const CHANGE_BOOK_QUANTITY_IN_CART = "REMOVE_BOOK_FROM_CART" as const;