export const FETCH_BOOKS_REQUESTED = 'FETCH_BOOKS_REQUESTED' as const;
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS' as const;
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE' as const;

export const FETCH_BOOK_DETAILS_REQUESTED = 'FETCH_BOOK_DETAILS_REQUESTED' as const;
export const FETCH_BOOK_DETAILS_SUCCESS = 'FETCH_BOOK_DETAILS_SUCCESS' as const;
export const FETCH_BOOK_DETAILS_FAILURE = 'FETCH_BOOK_DETAILS_FAILURE' as const;
export const RESET_BOOK_DETAILS_INFO = 'RESET_BOOK_DETAILS_INFO' as const;

export const CHANGE_VIEW = 'CHANGE_VIEW' as const;
export const CHANGE_SORT_TYPE = 'CHANGE_SORT_TYPE' as const;
export const CHANGE_PUBLISHER_FILTER_VALUE = 'CHANGE_PUBLISHER_FILTER_VALUE' as const;
export const CHANGE_AUTHORS_FILTER_VALUE = 'CHANGE_AUTHORS_FILTER_VALUE' as const;
export const CHANGE_DATE_FILTER_VALUE = 'CHANGE_DATE_FILTER_VALUE' as const;
export const UPDATE_SEARCH_QUERRY = 'UPDATE_SEARCH_QUERRY' as const;
export const SET_UTC_OFFSET = 'SET_UTC_OFFSET' as const;

export const UPDATE_BOOK_IN_CART = 'UPDATE_BOOK_IN_CART' as const;
export const CHANGE_BOOK_QUANTITY_IN_CART = 'REMOVE_BOOK_FROM_CART' as const;
