export const FETCH_NEW_BOOKS = "FETCH_NEW_BOOKS" as const;
export const FETCH_NEW_BOOKS_SUCCESS = "FETCH_NEW_BOOKS_SUCCESS" as const;
export const FETCH_NEW_BOOKS_ERROR = "FETCH_NEW_BOOKS_ERROR" as const;

export const FETCH_BOOK_DETAILS = "FETCH_BOOK_DETAILS" as const;
export const FETCH_BOOK_DETAILS_SUCCESS = "FETCH_BOOK_DETAILS_SUCCESS" as const;
export const FETCH_BOOK_DETAILS_ERROR = "FETCH_BOOK_DETAILS_ERROR" as const;